require 'date'

APP_NAME = "spectrometry_kit"

desc "builds <APP_NAME>.pde"
task :build do
	build
end

desc "automatically builds <APP_NAME>.pde when something in src/ changes"
task :autobuild do
  build
	require 'lib/filesystemwatcher'
	watcher = FileSystemWatcher.new
	watcher.addDirectory 'src', '**/*.java'
	watcher.sleepTime = 2
	watcher.start do |status,file|
	    if ([FileSystemWatcher::CREATED,
	    	FileSystemWatcher::MODIFIED,
	    	FileSystemWatcher::DELETED].include? status)
	        begin
	          build
          rescue
            puts "//// !!! Build failed !!! ////"
            puts $!
          end
	    end
	end
	
	watcher.join()
end

def build
	puts 'building... '+DateTime.now.to_s
	$:.push 'lib/sprockets'
	require 'sprockets'
	
	secretary = Sprockets::Secretary.new(
	  :load_path    => ['src'],
	  :source_files => ['src/application.java']
	)
	
	lines = Marshal.dump secretary.preprocessor.lines
	#File.open '.line_data.dat', 'w' do |f|
	#	f.print lines
	#end
	
	concatenation = secretary.concatenation
	
	concatenation.save_to(APP_NAME+".pde")
	
	puts "Build finished"
end 
